# Generated by Django 5.0.3 on 2024-03-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('publishDate', models.DateField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('popular', models.BooleanField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'api_news',
            },
        ),
    ]
